name: tests

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10']
        include:
          - os: ubuntu-latest
            python-version: '3.10'
            include-coverage: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            **/*main.txt
            **/*test.txt

      - name: Install dependencies
        run: >
          python3 -m pip install
          -r requirements/main.txt
          -r requirements/test.txt

      - name: Install Ubuntu dependencies
        if: runner.os == 'Linux'
        run: |
          REPO_NAME=mkvtoolnix.download
          GPG_NAME=gpg-pub-moritzbunkus.gpg
          GPG_PATH=/usr/share/keyrings/$GPG_NAME

          # Import MKVToolNix's public GPG key
          curl https://$REPO_NAME/$GPG_NAME --output $GPG_PATH

          # Add MKVToolNix's debian repository
          echo "\
          deb [arch=amd64 signed-by=$GPG_PATH] \
          https://$REPO_NAME/ubuntu/ $(lsb_release -sc) main\
          " \
          | sudo dd of=/etc/apt/sources.list.d/$REPO_NAME.list
          sudo apt update

          sudo apt install mkvtoolnix mediainfo

      - name: Install macOS dependencies
        if: runner.os == 'macOS'
        run: |
          MTN_NAME=MKVToolNix-$(\
          curl --silent https://formulae.brew.sh/api/formula/mkvtoolnix.json \
          | jq -r .versions.stable\
          )
          MTN_PATH=/Volumes/$MTN_NAME/$MTN_NAME.app/Contents/MacOS

          # Download and mount MKVToolNix's disk image
          curl https://mkvtoolnix.download/macos/$MTN_NAME.dmg \
          --output $MTN_NAME.dmg
          hdiutil attach $MTN_NAME.dmg

          cp $MTN_PATH/mkv* /usr/local/bin
          cp $MTN_PATH/libs/* /usr/local/lib
          brew install mediainfo

      - name: Install Windows dependencies
        if: runner.os == 'Windows'
        run: |
          choco install mkvtoolnix mediainfo

          # Add MKVToolNix to Windows PATH
          echo 'C:\Program Files\MKVToolNix' \
          | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Run tests
        if: ${{ !matrix.include-coverage }}
        run: pytest

      - name: Run tests with coverage
        if: ${{ matrix.include-coverage }}
        run: pytest --cov --cov-report xml

      - name: Upload coverage report as an artifact
        if: matrix.include-coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml


  upload-coverage:
    needs: main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download coverage report artifact
        uses: actions/download-artifact@v3

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
          fail_ci_if_error: true
          verbose: true
